main/urls.py
from django.urls import path, include
from . import views
from .views import PortfolioCreateView, portfolio_update_view, PortfolioDeleteView, PortfolioDataView, PortfolioDetailView
from .views import dashboard_view
from .views import custom_login

app_name = 'main'

urlpatterns = [
	path('', views.IndexView.as_view(), name="home"),
	path('accounts/', include('allauth.urls')),
	path('login/', custom_login, name='login'),
	path('contact/', views.ContactView.as_view(), name="contact"),
	path('portfolio/', views.PortfolioView.as_view(), name="portfolios"),
	path('portfolio/<slug:slug>', views.PortfolioDetailView.as_view(), name="portfolio"),
	path('dashboard/', dashboard_view, name='dashboard'),
    path('portfolio/add/', PortfolioCreateView.as_view(), name='portfolio_add'),
	path('portfolio/data/<int:portfolio_id>/', PortfolioDataView.as_view(), name='portfolio_data'),
	path('portfolio/<int:portfolio_id>/update/', portfolio_update_view, name='portfolio_update'),
    path('portfolio/<int:pk>/delete/', PortfolioDeleteView.as_view(), name='portfolio_delete'),
	path('blog/', views.BlogView.as_view(), name="blogs"),
	path('blog/<slug:slug>', views.BlogDetailView.as_view(), name="blog"),
	]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
import os

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/', include('allauth.urls')),
    
]

if os.path.isfile('env.py'):
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.utils import timezone
from django_summernote.fields import SummernoteTextField
from cloudinary.models import CloudinaryField
# Create your models here.

class Skill(models.Model):

    
    name = models.CharField(max_length=20, blank=True, null=True)
    score = models.IntegerField(default=80, blank=True, null=True)
    image = models.FileField(blank=True, null=True, upload_to="skills")
    is_key_skill = models.BooleanField(default=False)
    
    def __str__(self):
        return self.name

class UserProfile(models.Model):

    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='dir_on_cloudinary', blank=True)
    title = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    skills = models.ManyToManyField(Skill, blank=True)
    cv = models.FileField(blank=True, null=True, upload_to="cv")

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'

class ContactProfile(models.Model):
    
    class Meta:

        ordering = ["timestamp"]

    timestamp = models.DateTimeField(auto_now_add=True)
    name = models.CharField(verbose_name="Name", max_length=100)
    email = models.EmailField(verbose_name="Email")
    message = models.TextField(verbose_name="Message")

    def __str__(self):
        return f'{self.name}'



class Testimonial(models.Model):

    class Meta:

        ordering = ["name"]

    thumbnail = models.ImageField(upload_to='dir_on_cloudinary', blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    role = models.CharField(max_length=200, blank=True, null=True)
    quote = models.CharField(max_length=500, blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name



class Portfolio(models.Model):

    class Meta:
         ordering = ["name"]

    created_on = models.DateTimeField(default=timezone.now)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='dir_on_cloudinary', blank=True)
    url = models.URLField(blank=True, null=True)
    slug = models.SlugField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Portfolio, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/portfolio/{self.slug}"


class Blog(models.Model):

    class Meta:

        ordering = ["-timestamp"]

    timestamp = models.DateTimeField(default=timezone.now)
    author = models.CharField(max_length=200, blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = SummernoteTextField(blank=True, null=True)
    slug = models.SlugField(null=True, blank=True)
    image = models.ImageField(upload_to='dir_on_cloudinary', blank=True)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Blog, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/blog/{self.slug}"


class Certificate(models.Model):


    date = models.DateTimeField(default=timezone.now)
    name = models.CharField(max_length=50, blank=True, null=True)
    title = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    image = models.ImageField(upload_to='dir_on_cloudinary', blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

main/forms.py
from django import forms
from .models import ContactProfile, Portfolio
from django_summernote.fields import SummernoteTextFormField, SummernoteTextField
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget


class ContactForm(forms.ModelForm):

	name = forms.CharField(max_length=100, required=True,
		widget=forms.TextInput(attrs={
			'placeholder': '*Full name..',			
			}))
	email = forms.EmailField(max_length=254, required=True, 
		widget=forms.TextInput(attrs={
			'placeholder': '*Email..',			
			}))
	message = forms.CharField(max_length=1000, required=True, 
		widget=forms.Textarea(attrs={
			'placeholder': '*Message..',
			'rows': 6,		
			}))

	class Meta:
		model = ContactProfile
		fields = ('name', 'email', 'message',)



class PortfolioForm(forms.ModelForm):
    class Meta:
        model = Portfolio
        fields = ['name', 'description', 'body', 'url', 'image']


class UpdatePortfoliosForm(forms.ModelForm):
    class Meta:
        model = Portfolio
        fields = ['name', 'description', 'body', 'url', 'image']

main/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, DeleteView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import ContactForm, UpdatePortfoliosForm, PortfolioForm
from .models import UserProfile, Blog, Portfolio, Testimonial, Certificate

def custom_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f"Welcome back, {username}!")
                return redirect('main:home')  # Redirect to the home page after login
            else:
                messages.error(request, "Invalid username or password.")
    else:
        form = AuthenticationForm()
    return render(request, 'registration/login.html', {'form': form})

class IndexView(TemplateView):
    template_name = "main/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["testimonials"] = Testimonial.objects.filter(is_active=True)
        context["certificates"] = Certificate.objects.filter(is_active=True)
        context["blogs"] = Blog.objects.filter(is_active=True)
        context["portfolio"] = Portfolio.objects.filter(is_active=True)
        return context

class ContactView(CreateView):
    template_name = "main/contact.html"
    form_class = ContactForm
    success_url = "/"

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Thank you. I will be in touch soon.')
        return super().form_valid(form)

class PortfolioView(ListView):
    model = Portfolio
    template_name = "main/portfolio.html"
    paginate_by = 10

    def get_queryset(self):
        return self.model.objects.filter(is_active=True)

from .forms import PortfolioForm

def dashboard_view(request):
    if request.method == 'POST':
        operation = request.POST.get('operation')
        if operation == 'create':
            form = PortfolioForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                messages.success(request, 'Portfolio item created successfully.')
                return redirect('main:dashboard')
        elif operation == 'update':
            portfolio_id = request.POST.get('portfolio_id')
            portfolio = get_object_or_404(Portfolio, pk=portfolio_id)
            form = PortfolioForm(request.POST, request.FILES, instance=portfolio)
            if form.is_valid():
                form.save()
                messages.success(request, 'Portfolio item updated successfully.')
                return redirect('main:dashboard')
    else:
        form = PortfolioForm()
    portfolios = Portfolio.objects.all()
    return render(request, 'main/dashboard.html', {'portfolios': portfolios, 'form': form})


class PortfolioCreateView(LoginRequiredMixin, CreateView):
    model = Portfolio
    fields = ['name', 'description', 'body', 'url', 'image']
    template_name = 'main/dashboard.html'  # Create a new template for the form
    success_url = reverse_lazy('main:portfolio')  # Redirect to the portfolio page after successful creation

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

def portfolio_update_view(request, portfolio_id):
    portfolio = Portfolio.objects.get(pk=portfolio_id)
    if request.method == 'POST':
        form = PortfolioForm(request.POST, instance=portfolio)
        if form.is_valid():
            form.save()
            # Redirect to dashboard or display a success message
    else:
        form = PortfolioForm(instance=portfolio)
    return render(request, 'main/portfolio_update_modal.html', {'form': form, 'portfolio': portfolio})

class PortfolioDataView(View):
    def get(self, request, portfolio_id):
        portfolio = Portfolio.objects.get(pk=portfolio_id)
        data = {
            'name': portfolio.name,
            'description': portfolio.description,
            'body': portfolio.body,
            'url': portfolio.url,
            
            
        }
        return JsonResponse(data)

class PortfolioDeleteView(LoginRequiredMixin, DeleteView):
    model = Portfolio
    success_url = reverse_lazy('main:dashboard')  # Redirect to the portfolio page after successful deletion

class PortfolioDetailView(DetailView):
    model = Portfolio
    template_name = "main/portfolio-detail.html"
    fields = ['name', 'description', 'body', 'url', 'image']

class BlogView(ListView):
    model = Blog
    template_name = "main/blog.html"
    paginate_by = 10

    def get_queryset(self):
        return self.model.objects.filter(is_active=True)

class BlogDetailView(DetailView):
    model = Blog
    template_name = "main/blog-detail.html"

    def get_queryset(self):
        return Blog.objects.filter(slug=self.kwargs['slug'], is_active=True)

    def get_object(self):
        queryset = self.get_queryset()
        obj = get_object_or_404(queryset)
        return obj

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{%endblock %}</title>
    <meta name="author" content="Carl Sparks Web Developer">
    <link rel="canonical" href="{{request.path}}"/>
    <link rel="home" href="{% url 'main:home' %}"/>
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="keywords" content="{% block keywords %}{% endblock %}">
    <link rel="shortcut icon" type="image/x-icon" class="logo-icon" href="{% static 'images/logo-mini-fav.png' %}">
    <link rel="apple-touch-icon" type="image/jpg" class="logo-icon" href="{% static 'images/logo-mini-fav.png' %}">

    <!-- Start CSS -->
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/2d77eab3e2.js" crossorigin="anonymous"></script>
    
    {% block extend_header%}{%endblock%}
    <!-- End CSS -->

  </head>
  <body>
    
    
    {% include 'main/partials/messages.html' %}
    {% include 'main/partials/nav.html' %}

    {% block content %}
    {% endblock %}

    {% include 'main/partials/footer.html' %}

    <!-- Start Scripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>   
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>

    {% block extend_footer %}{%endblock%}
    <!-- End Scripts -->
 
  </body>
</html>

main/templates/main/blog-detail.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section>
  <div class="innerPageBannerCol weather-card">
    <div class="container mt-4">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-6">
          <div class="bannerContent">
            <h1 class="xlTitle">{{object.name|title}}</h1>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-auto">
          <div class="authorCol">
            <h4 class="smTitle pb-1">{{object.author|title}}</h4>
          </div>
        </div>
        <div class="col-md">
          <h4 class="smTitle pb-1">{{object.timestamp.date}}</h4>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="sectionSpaceSm">
    <div class="container">
      <!-- Render the main text of the blog -->
      {{ object.body|safe }}
    </div>
    <div class="container">
     
    </div>
  </div>
</section>


{% endblock %}
<!-- ================================
End Content
================================= -->
   

main/templates/main/blog.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section>
  <div class="innerPageBannerCol weather-card">
    <div class="container mt-4">
      <div class="row g-4 justify-content-center">
        <div class="col-auto">
          <div class="bannerContent">
            <h1 class="col-auto xlTitle mb-5">See my recent blogs below</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div>
    <div class="container">
      <div class="portfolioContentMain">
        <div class="row g-3 g-md-4 g-lg-5 portfolioRow">
          {% for obj in object_list %}
          <div class="col-md-6 pColMain">
            <div class="pCol">
              <a href="{% url 'main:blog' slug=obj.slug %}" >
              <img src="{{obj.image.url}}" alt="..." class="pImg">
              </a>
            </div>
          </div>
          {% endfor %}

        </div>
      </div>
    </div>
  </div>
</section>
<!-- ================================
End Content
================================= -->
{%endblock%} 
    

main/templates/main/dashboard.html
{% extends 'main/base.html' %}
{% load static %}

<!-- Start Content -->
{% block content %}
<section>
  <div class="innerPageBannerCol">
    <div class="container mt-4">
      <div class="row g-3 g-m-3 text-center">
        <div class="col">
          <div class="bannerContent">
            <h2>Make your updates here</h2>
          </div>
        </div>
        <div class="col-md-2">
          <a href="{% url 'admin:index' %}" class="btn btnPrimary">Go to Admin</a>
        </div>
      </div>
      <div class="row pt-3 text-center">
        <div class="col">
        <p class="pt-3">This is a quick and nicer alternative to the admin panel. <br> With space for extras.</p>
      </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="lighterBg">
    <div class="container-xl">
      <div class="row">
        <h4 class="col pt-2 mt-2 pb-2 text-center text-decoration-underline" id="add-new-entry">Add or Edit a Portfolio exhibit below.</h4>
        <div class="dropdown">
          <button class="col-8 offset-2 mt-3 mb-3 btn btnPrimary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Choose a portfolio
          </button>
          <!-- Dropdown menu -->
          <ul class="dropdown-menu">
            {% for portfolio in portfolios %}
                <li>
                    <a class="dropdown-item" href="#" onclick="populateForm({{ portfolio.id }})">
                        {{ portfolio.name }}
                    </a>
                </li>
            {% endfor %}
          </ul>
        </div>
      </div>
      <div class="col p-3">
        <form id="UpdatePortfoliosForm" method="POST" action="{% url 'main:dashboard' %}" enctype="multipart/form-data">
          {% csrf_token %}
          <!-- Add a hidden field to indicate the operation -->
          <input type="hidden" name="operation" id="id_operation" value="create">
          <input type="hidden" name="portfolio_id" id="id_portfolio_id" value="">
          <!-- Form fields -->
          {{ form.as_p }}
          <!-- Submit button -->
          <div class="text-center">
            <input class="btn btnPrimary mb-3" type="submit" value="Submit">
          </div>
        </form>
      <div class="portfolio-items">
        <div class="row">
          {% for portfolio in portfolios %}
          <div class="col-auto mb-3">
            <h3 class="portfolio-title">{{ portfolio.name }}</h3>
            <!-- Add delete button with a form -->
            <form class="d-inline" method="post" action="{% url 'main:portfolio_delete' portfolio.id %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger">Delete</button>
            </form>
          </div>
          {% endfor %}
        </div>
      </div>
      </div>
    </div>
  </div>
</section>

<!-- End Content -->
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->

<!-- class="weather-card" -->

{% block content %}
<div>
<section>
  <div class="bannerSection weather-card mt-2">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center mt-1">
        <div class="col-md-auto">
          <div class="bannerUserImg mt-2">
            <img src="{{me.userprofile.image.url}}" alt="{{me.first_name|title}} {{me.last_name|title}} avatar">
          </div>
        </div>
        <div class="col-md order-md-last">
          <div class="bannerContent p-3 mt-1">
            <h1 class="xlTitle pb-3">Hi, I'm {{me.first_name|title}}, <br> a {{me.userprofile.title}} </br></h1>
            <p>{{me.userprofile.bio}}</p>
            <div class="bannerBtnCol">
              <div class="row text-center">
                <div class="col-auto mt-2">
                  <a download href="{{me.userprofile.cv.url}}" class="btn btnPrimary">Download CV</a>
                </div>
                <div class="col-auto mt-2">
                  <a href="{% url 'main:contact' %}" class="btn btnOutline">Contact</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<div class="testimonialCol">
  <div class="container">
    <div class="row pb-3">
  <h4 class="lgTitle pb-3 d-block">Testimonials</h4>
  <div class="testimonialSlider">
    <div class="Col-8 offset-1 p-1 swiper testimonialSwiper">
      <div class="swiper-wrapper">
        {% for t in testimonials %}
        {% if t.is_active %}
        <div class="swiper-slide">
          <div class="testimonialCard p-2">
            <div class="row align-items-center">
              <div class="col-sm-auto">
                <div class="tImgCol">
                  <img src="{{t.thumbnail.url}}" alt="...">
                </div>
              </div>
              <div class="col-sm">
                <div class="tContentCol">
                  <h4 class="xsTitle bold">{{t.name}} - {{t.role}}</h4>
                  <p>{{t.quote}}</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endif %}
        {% endfor %}

      </div>
      <div class="test-swiper-button-next swiper-button-next swiperBtnStyle"></div>
      <div class="test-swiper-button-prev swiper-button-prev swiperBtnStyle"></div>
    </div>
  </div>
</div>
</div>
</div>

<section>
  <div class="sectionSpaceSm lighterBg">
    <div class="container">
      <div class="row pb-3">
        <div class="col">
          <h4 class="lgTitle pb-3">Certificates</h4>
        </div>

      </div>
      <div class="sliderOuter text-center">
        <div class="swiper certificatesSlider">
          <div class="swiper-wrapper">
            {% for c in certificates %}
            {% if c.is_active %}
            <div class="swiper-slide">
              <div class="cardStyle1">
                <h4 class="mdTitle cs1Title">
                  <a href="javascript:void(0)">{{c.title}}</a>
                </h4>
                <ul class="cardOptionCol">
                  <li><img src="{{c.image.url}}" alt="Certificate image"></li>
                  <li>{{c.date.date}}</li>
                  <li>{{c.name|title}}</li>
                </ul>
                <p>{{c.description}}</p>
              </div>
            </div>
            {% endif %}
            {% endfor %}
            
          </div>
        </div>            
        <div class="cert-swiper-button-next swiper-button-next swiperBtnStyle"></div>
        <div class="cert-swiper-button-prev swiper-button-prev swiperBtnStyle"></div>
        <div class="swiper-pagination swiperPaginationStyle posInitial"></div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="sectionSpace">
    <div class="container">
      <div class="portfolioCol">
        <div class="row pb-3">
          <div class="col">
            <h4 class="lgTitle pb-3">Featured Work</h4>
          </div>
          <div class="col-auto">
            <a href="{% url 'main:portfolios' %}" class="simpleLink">View all</a>
          </div>
        </div>
        {% for p in portfolio %}
        {% if p.is_active %}
        <div class="portfolioCard text-center">
          <div class="row g-4 align-items-center">
            <div class="col-md-auto">
              <div class="portfolioImgCol">
                <a href="{% url 'main:portfolio' slug=p.slug %}"><img src="{{p.image.url}}" alt="..."></a>
              </div>
            </div>
            <div class="col-md">
              <div class="portfolioContentCol">
                <h4 class="lgTitle"><a href="{% url 'main:portfolio' slug=p.slug %}">{{p.name}}</a></h4>
                <ul class="portfolioOption">
                  <li><span class="dateLbl">{{p.date.year}}</span></li>
                </ul>
                <p>{{p.description}}</p>
              </div>
            </div>
          </div>
        </div>
        {% endif %}
        {% endfor %}
        
      </div>

    </div>
  </div>
</section>

<section>
  <div class="sectionSpace pt-0">
    <div class="container">
      <div class="row">
        <div class="col">
          <h4 class="lgTitle pb-3">Coding Skills</h4>
          <div class="row">
            <div class="col-2">
              <div class="keySkillCol">
                {% for sk in me.userprofile.skills.all %}
                {% if sk.is_key_skill %}
                <div class="keySkillCard">
                  {% if sk.image %}
                  <div class="ksIconCol">
                    <img src="{{sk.image.url}}" alt="...">
                  </div>
                  {% endif %}
                  <span class="ksText">{{sk.name}}</span>
                </div>
                {% endif %}
                {% endfor %}
              </div>
            </div>
            <div class="col-8 offset-2">
              <div class="progressCol">
                {% for sk in me.userprofile.skills.all %}
                {% if sk.is_key_skill %}
                <div class="progressCol">
                  <span class="progressLbl"><h5>{{sk.name}}</h5></span>
                  <div class="row g-2 align-items-center">
                    <div class="col ml-2">
                      <div class="progress progressStyle">
                        <div class="progress-bar" role="progressbar" style="width: {{sk.score}}%" aria-valuenow="{{sk.score}}" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                    </div>
                    <div class="col-auto">
                      <span class="pLbl">{{sk.score}}%</span>
                    </div>
                  </div>
                </div>
                {% endif %}
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<section>
  <div class="sectionSpaceSm lighterBg mr-2">
    <div class="container">
      <div class="row pb-3">
        <div class="col">
          <h4 class="lgTitle pb-3">Recent posts</h4>
        </div>
        <div class="col-auto">
          <a href="{% url 'main:blogs' %}" class="simpleLink">View all</a>
        </div>
      </div>
      <div class="sliderOuter">
        <div class="swiper blogSlider">
          <div class="swiper-wrapper">
           
            {% for b in blogs %}
            {% if b.is_active %}
            <div class="swiper-slide">
              <div class="cardStyle1">
                <h4 class="mdTitle cs1Title text-center pt-3">
                  <a href="{% url 'main:blog' slug=b.slug %}">{{ b.name }}</a>
                </h4>
                <ul class="cardOptionCol">
                  <li>{{ b.timestamp.date }}</li>
                  <li>{{ b.author }}</li>
                </ul>
                <!-- Display the image -->
                <img src="{{ b.image.url }}" alt="{{ b.name }}" class="img-fluid">
                <p class="pt-2">{{ b.description }}</p>
              </div>
            </div>
           
            {% endif %}
            {% endfor %}
          </div>
        </div>
        <!-- Add navigation buttons -->
        <div class="swiper-button-next blog-swiper-button-next swiperBtnStyle"></div>
        <div class="swiper-button-prev blog-swiper-button-prev swiperBtnStyle"></div>
        <!-- Add pagination -->
        <div class="swiper-pagination blog-swiper-pagination swiperPaginationStyle posInitial"></div>
      </div>
    </div>
  </div>
</section>

</div>
{% endblock %}
<!-- ================================
End Content
================================= -->